# Site
name: 'Towards Data Science & Technology'
description: 'Data science is a rapidly growing field with applications in almost every industry. It involves the use of scientific methods, processes, algorithms, and systems to extract knowledge and insights from data.'
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'exmgks@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    adam:
      name:           Adam
      site:           https://towardsdatascience.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Adam, I love writing on AI and Data Science"
      email:          exmgks@gmail.com
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: epic
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]